### ISSUE TITLE
技术展示区鼠标移到黑幕上没有反应

### ISSUE THREAD

**Issue by VeryrrDefine** [gumojj/homepage#2]
使用浏览器Chrome/109.0.0.0
在网页上https://gumojj.github.io/homepage/webgame/jishu/index.html
将鼠标移到黑幕上没有反应，只有选中黑幕才能看到文字

**Comment by gumojj** [comment]
好的，会尽快修复

**Comment by VeryrrDefine** [comment]
修复个牛魔
